// <auto-generated>disable stylecop</auto-generated>
namespace ZerosTwitterClient
{
    partial class TwitterLogin
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.authApp = new System.Windows.Forms.Button();
            this.applicationPinBox = new System.Windows.Forms.TextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.consumerSecretBox = new System.Windows.Forms.TextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.consumerKeyBox = new System.Windows.Forms.TextBox();
            this.reqAccessToken = new System.Windows.Forms.Button();
            this.tableLayoutPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 2;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.Controls.Add(this.authApp, 1, 4);
            this.tableLayoutPanel1.Controls.Add(this.applicationPinBox, 1, 3);
            this.tableLayoutPanel1.Controls.Add(this.label3, 0, 3);
            this.tableLayoutPanel1.Controls.Add(this.consumerSecretBox, 1, 1);
            this.tableLayoutPanel1.Controls.Add(this.label2, 0, 1);
            this.tableLayoutPanel1.Controls.Add(this.label1, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.consumerKeyBox, 1, 0);
            this.tableLayoutPanel1.Controls.Add(this.reqAccessToken, 1, 2);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 5;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(695, 229);
            this.tableLayoutPanel1.TabIndex = 0;
            // 
            // authApp
            // 
            this.authApp.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.authApp.Dock = System.Windows.Forms.DockStyle.Fill;
            this.authApp.Location = new System.Drawing.Point(152, 177);
            this.authApp.Name = "authApp";
            this.authApp.Size = new System.Drawing.Size(540, 49);
            this.authApp.TabIndex = 7;
            this.authApp.Text = "Authorize Application";
            this.authApp.UseVisualStyleBackColor = true;
            this.authApp.Click += new System.EventHandler(this.AuthAppClick);
            // 
            // applicationPinBox
            // 
            this.applicationPinBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.applicationPinBox.Location = new System.Drawing.Point(159, 144);
            this.applicationPinBox.Margin = new System.Windows.Forms.Padding(10);
            this.applicationPinBox.Name = "applicationPinBox";
            this.applicationPinBox.Size = new System.Drawing.Size(526, 20);
            this.applicationPinBox.TabIndex = 6;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label3.Location = new System.Drawing.Point(3, 134);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(143, 40);
            this.label3.TabIndex = 5;
            this.label3.Text = "Application PIN";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // consumerSecretBox
            // 
            this.consumerSecretBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.consumerSecretBox.Location = new System.Drawing.Point(159, 50);
            this.consumerSecretBox.Margin = new System.Windows.Forms.Padding(10);
            this.consumerSecretBox.Name = "consumerSecretBox";
            this.consumerSecretBox.Size = new System.Drawing.Size(526, 20);
            this.consumerSecretBox.TabIndex = 3;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label2.Location = new System.Drawing.Point(3, 40);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(143, 40);
            this.label2.TabIndex = 2;
            this.label2.Text = "Application Consumer Secret";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label1.Location = new System.Drawing.Point(3, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(143, 40);
            this.label1.TabIndex = 0;
            this.label1.Text = "Application Consumer Key";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // consumerKeyBox
            // 
            this.consumerKeyBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.consumerKeyBox.Location = new System.Drawing.Point(159, 10);
            this.consumerKeyBox.Margin = new System.Windows.Forms.Padding(10);
            this.consumerKeyBox.Name = "consumerKeyBox";
            this.consumerKeyBox.Size = new System.Drawing.Size(526, 20);
            this.consumerKeyBox.TabIndex = 1;
            // 
            // reqAccessToken
            // 
            this.reqAccessToken.Dock = System.Windows.Forms.DockStyle.Fill;
            this.reqAccessToken.Location = new System.Drawing.Point(152, 83);
            this.reqAccessToken.Name = "reqAccessToken";
            this.reqAccessToken.Size = new System.Drawing.Size(540, 48);
            this.reqAccessToken.TabIndex = 4;
            this.reqAccessToken.Text = "Request Access Token";
            this.reqAccessToken.UseVisualStyleBackColor = true;
            this.reqAccessToken.Click += new System.EventHandler(this.Button1Click);
            // 
            // TwitterLogin
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(695, 229);
            this.Controls.Add(this.tableLayoutPanel1);
            this.Name = "TwitterLogin";
            this.Text = "OAuth Application Configuration";
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.TextBox consumerSecretBox;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TextBox consumerKeyBox;
        private System.Windows.Forms.Button reqAccessToken;
        private System.Windows.Forms.Button authApp;
        private System.Windows.Forms.TextBox applicationPinBox;
        private System.Windows.Forms.Label label3;
    }
}